apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gcloud-cron.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "gcloud-cron.name" . }}
    helm.sh/chart: {{ include "gcloud-cron.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels.configMap }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations.configMap }}
  annotations:
    {{- with .Values.annotations.configMap }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  entrypoint.sh: {{ .Values.entrypoint | quote }}
  {{- if .Values.vault.enabled }}
  vault_ca.pem: {{ required "Vault CA is required" .Values.vault.ca | quote }}
  vault_agent.hcl: |
    pid_file = "/pid"
    exit_after_auth = true

    auto_auth {
      method "kubernetes" {
        mount_path = "auth/{{ required "Auth mount path is needed" .Values.vault.auth.path }}"

        config {
          role = "{{ required "Vault Auth Role is needed" .Values.vault.auth.role }}"
          token_path = "/var/run/secrets/kubernetes.io/serviceaccount/token"
        }
      }

      sink "file" {
        config {
          path = "/vault/token"
        }
      }
    }

    template {
      left_delimiter = "||"
      right_delimiter = "||"

      contents = <<-EOF
      ||- with secret "{{ required "GCP secrets backend path is needed" .Values.vault.gcp.path }}" -||
      ||- .Data.private_key_data | base64Decode -||
      ||- end -||
      EOF

      destination = "/gcp/service_account.json"
      create_dest_dirs = true
      error_on_missing_key = true
    }
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gcloud-cron.fullname" . }}-additional
  labels:
    app.kubernetes.io/name: {{ include "gcloud-cron.name" . }}
    helm.sh/chart: {{ include "gcloud-cron.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels.configMap }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.annotations.configMap }}
  annotations:
    {{- with .Values.annotations.configMap }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
data:
  {{- with .Values.additionalConfig }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
