# See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#schedule
schedule: "0 3 * * *"
# See https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#concurrency-policy
concurrencyPolicy: "Allow"

successfulJobsHistoryLimit: "10"
failedJobsHistoryLimit: "10"

ttlSecondsAfterFinished: 86400

image:
  repository: google/cloud-sdk
  tag: alpine
  pullPolicy: IfNotPresent

env: {}

nameOverride: ""
fullnameOverride: ""

serviceAccount: "gcloud"

vault:
  enabled: true
  image: vault
  tag: 1.0.3
  pullPolicy: IfNotPresent
  address: https://vault.service.consul:8200
  # PEM encoded CA used to issue Vault's Certificate
  ca: ""
  auth:
    path: "kubernetes"
    role: ""
  gcp:
    path: ""
  env: []

resources:
  vaultAgent: {}
  backup:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

labels:
  serviceAccount: {}
  cronJob: {}
  pods: {}
  configMap: {}

annotations:
  serviceAccount: {}
  cronJob: {}
  pods: {}
  configMap: {}


# Additional files that will be mounted at `additionalMountPoint`
# The keys will be the filename
additionalConfig: {}

additionalMountPoint: /additional

# Script to run as entrypoint
entrypoint: |
  #!/bin/sh
  gcloud --version
